# Generated by Django 5.0.3 on 2025-08-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='race',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wants_sponsorship',
        ),
    ]
